from server.handlers.profile_handler import ProfileHandler
from server.handlers.lesson_handler import LessonHandler
from server.handlers.index_handler import IndexHandler
from server.handlers.login_handler import LoginHandler
from server.handlers.google_oauth2_login_handler import GoogleOAuth2LoginHandler